# Generated by Django 5.0.2 on 2026-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('taluka', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('survey_number', models.CharField(max_length=100)),
                ('survey_number_part1', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('language', models.CharField(default='en_us', max_length=10)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('session_state_json', models.TextField(blank=True, null=True)),
                ('result_json', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_runs',
            },
        ),
    ]
