# Generated by Django 5.2.17 on 2026-08-06 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('district_name', models.CharField(max_length=100)),
                ('taluka_name', models.CharField(max_length=100)),
                ('village_name', models.CharField(max_length=100)),
                ('survey_number', models.CharField(blank=True, default='', max_length=100)),
                ('subdivision_number', models.CharField(blank=True, default='', max_length=100)),
                ('property_number', models.CharField(blank=True, default='', max_length=100)),
                ('district_code', models.CharField(blank=True, default='', max_length=50)),
                ('taluka_code', models.CharField(blank=True, default='', max_length=50)),
                ('village_code', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('district_value', models.CharField(max_length=50)),
                ('district_label', models.CharField(max_length=100)),
                ('taluka_value', models.CharField(max_length=50)),
                ('taluka_label', models.CharField(max_length=100)),
                ('village_value', models.CharField(max_length=50)),
                ('village_label', models.CharField(max_length=100)),
                ('property_number', models.CharField(max_length=100)),
                ('year_from', models.IntegerField()),
                ('year_to', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('current_step', models.CharField(default='initial', max_length=100)),
                ('total_steps', models.IntegerField(default=0)),
                ('completed_steps', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='igr_api.property')),
            ],
        ),
        migrations.CreateModel(
            name='SourceRun',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('source_name', models.CharField(default='igr', max_length=50)),
                ('source_year', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('workflow_step', models.CharField(blank=True, default='', max_length=100)),
                ('run_dir', models.CharField(blank=True, default='', max_length=255)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_runs', to='igr_api.workflowrun')),
            ],
        ),
    ]
