@echo off
if not exist venv (
    echo Creating virtual environment using Python 3.11...
    ..\..\backend\venv\Scripts\python.exe -m venv venv
)
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Running Django database migrations...
python manage.py migrate
echo Starting Django Backend on port 8002...
python manage.py runserver 8002
pause
