@echo off
echo Setting up Python virtual environment...
python -m venv venv
call venv\Scripts\activate
echo Installing dependencies...
pip install -r requirements.txt
echo Running Django database migrations...
python manage.py migrate
echo Starting Django Backend on port 8001...
python manage.py runserver 8001
pause
